import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {database} from '../local-db.mjs';
import {createService,stripeSignature} from '../service.mjs';
import {providers,cents} from '../providers.mjs';
const admin='test-admin-token-with-more-than-32-characters';
const address={name:'Test Reader',street1:'Teststrasse 1',city:'Zarrentin',postcode:'19246',phone_number:'+49 000 000000',country_code:'DE'};
const body=()=>({email:'reader@example.invalid',address:{...address},items:[{sku:'CBB_001_EN_PB',quantity:1}]});
function fixture(mode='simulation',provider) {const db=database();const service=createService({MODE:mode,ADMIN_TOKEN:admin,DB:db,STRIPE_KEY:mode==='sandbox'?'sk_test_fixture':undefined},provider);return {db,service};}
async function request(service,path,data,token,authenticated=false,origin='http://127.0.0.1:8093') {
  return service.route(new Request(origin+path,{method:data===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',...(token?{'X-Order-Token':token}:{}),...(authenticated?{Authorization:`Bearer ${admin}`}:{})},...(data===undefined?{}:{body:JSON.stringify(data)})}));
}
async function prepared(service) {const q=await service.quote(body());let r=await request(service,`/api/orders/${q.id}/checkout`,{accepted_test:true},q.token);assert.equal(r.status,200);r=await request(service,`/api/admin/orders/${q.id}/pay`,{},undefined,true);assert.equal(r.status,200);return q;}
test('complete local order, exactly one print job, shipment, invoice draft and message outbox',async()=>{const {service,db}=fixture();const q=await prepared(service);assert.equal((await service.get(q.id)).status,'PAID');await service.submit(q.id);await assert.rejects(()=>service.submit(q.id));await service.poll(q.id);assert.equal((await service.get(q.id)).status,'SHIPPED');const messages=await db.prepare('SELECT * FROM outbox').all();assert.equal(messages.results.length,2);const documents=(await db.prepare('SELECT * FROM documents').all()).results;assert.equal(documents.length,1);assert.equal(JSON.parse(documents[0].data).legal_status,'DRAFT_NOT_A_TAX_INVOICE');db.close();});
test('duplicate payments, distinct webhook IDs and concurrent submissions do not duplicate',async()=>{const {service,db}=fixture();const q=await prepared(service);const o=await service.get(q.id);const session={id:o.session_id,client_reference_id:o.id,amount_total:o.data.total,currency:o.data.currency,livemode:false,payment_status:'paid'};await service.paid(o.id,session,'evt_duplicate');const results=await Promise.allSettled([service.submit(o.id),service.submit(o.id)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal((await db.prepare("SELECT * FROM events WHERE kind='PAYMENT_VERIFIED'").all()).results.length,1);db.close();});
test('concurrent different payment event IDs create a single receipt',async()=>{const {service,db}=fixture();const q=await service.quote(body());await request(service,`/api/orders/${q.id}/checkout`,{accepted_test:true},q.token);const o=await service.get(q.id);const s={id:o.session_id,client_reference_id:o.id,amount_total:o.data.total,currency:o.data.currency,livemode:false,payment_status:'paid'};await Promise.allSettled([service.paid(o.id,s,'evt_a'),service.paid(o.id,s,'evt_b')]);assert.equal((await db.prepare('SELECT * FROM outbox').all()).results.length,1);db.close();});
test('public order excludes address and financial margin; token and admin auth required',async()=>{const {service,db}=fixture();const q=await prepared(service);assert.equal((await request(service,`/api/orders/${q.id}`)).status,403);const response=await request(service,`/api/orders/${q.id}`,undefined,q.token);const data=await response.json();assert.equal(data.address,undefined);assert.equal(data.margin,undefined);assert.equal(data.token,undefined);assert.equal((await request(service,'/api/admin/orders')).status,401);db.close();});
test('simulation rejects remote hosts, cross-origin writes and real customer mail',async()=>{const {service,db}=fixture();assert.equal((await request(service,'/api/catalog',undefined,undefined,false,'https://shop.example.com')).status,403);const req=new Request('http://127.0.0.1:8093/api/quote',{method:'POST',headers:{Origin:'https://evil.invalid','Content-Type':'application/json'},body:JSON.stringify(body())});assert.equal((await service.route(req)).status,403);await assert.rejects(()=>service.quote({...body(),email:'real@example.com'}));db.close();});
test('unpaid orders cannot print or refund; checkout needs acknowledgment',async()=>{const {service,db}=fixture();const q=await service.quote(body());await assert.rejects(()=>service.submit(q.id));await assert.rejects(async()=>service.refund(await service.get(q.id),{amount:100,request_id:'unpaid-refund'}));assert.equal((await request(service,`/api/orders/${q.id}/checkout`,{},q.token)).status,400);db.close();});
test('forged client price ignored; invalid quantities, duplicate lines and country rejected',async()=>{const {service,db}=fixture();const q=await service.quote({...body(),total:1,items:[{sku:'CBB_001_EN_PB',quantity:1,unit:1}]});assert.equal(q.total,3140);for(const quantity of [0,11,1.2,'1'])await assert.rejects(()=>service.quote({...body(),items:[{sku:'CBB_001_EN_PB',quantity}]}));await assert.rejects(()=>service.quote({...body(),items:[...body().items,...body().items]}));await assert.rejects(()=>service.quote({...body(),address:{...address,country_code:'ZZ'}}));db.close();});
test('all five planned markets quote in selected currency; US state required',async()=>{const {service,db}=fixture();for(const [country_code,currency] of Object.entries({DE:'EUR',US:'USD',GB:'GBP',CA:'CAD',AU:'AUD'})){const q=await service.quote({...body(),address:{...address,country_code,state_code:'CA'}});assert.equal(q.currency,currency);}await assert.rejects(()=>service.quote({...body(),address:{...address,country_code:'US'}}));db.close();});
test('payment amount, currency, reference, session and live mismatches rejected',async()=>{const {service,db}=fixture();const q=await service.quote(body());await request(service,`/api/orders/${q.id}/checkout`,{accepted_test:true},q.token);const o=await service.get(q.id);const valid={id:o.session_id,client_reference_id:o.id,amount_total:o.data.total,currency:o.data.currency,livemode:false,payment_status:'paid'};for(const change of [{amount_total:1},{currency:'USD'},{client_reference_id:'other'},{id:'cs_test_other'},{livemode:true},{payment_status:'unpaid'}])await assert.rejects(()=>service.paid(o.id,{...valid,...change},'evt_wrong'));assert.equal((await service.get(q.id)).status,'PAYMENT_PENDING');db.close();});
test('withdrawal is durable, repeat safe, creates receipt and prevents printing',async()=>{const {service,db}=fixture();const q=await prepared(service);const o=await service.get(q.id);const w=await service.withdrawal(o,{note:'Test'});assert.equal((await service.withdrawal(o,{})).request_id,w.request_id);await assert.rejects(()=>service.submit(q.id));assert.equal((await db.prepare('SELECT * FROM requests').all()).results.length,1);db.close();});
test('partial refunds cap remaining amount and block printing; full refund closes order',async()=>{const {service,db}=fixture();const q=await prepared(service);await service.refund(await service.get(q.id),{amount:100,request_id:'refund-first'});await assert.rejects(()=>service.submit(q.id));await assert.rejects(async()=>service.refund(await service.get(q.id),{amount:q.total,request_id:'refund-excess'}));await service.refund(await service.get(q.id),{amount:q.total-100,request_id:'refund-second'});assert.equal((await service.get(q.id)).status,'REFUNDED');db.close();});
test('refund after printing requires manual resolution',async()=>{const {service,db}=fixture();const q=await prepared(service);await service.submit(q.id);await assert.rejects(async()=>service.refund(await service.get(q.id),{amount:100,request_id:'too-late-refund'}));db.close();});
const approvedFixture={sku:'TEST_PRODUCT',approved:true,pages:32,package:'test-package',prices:{EUR:100},print_assets:{cover:{url:'https://example.invalid/cover.pdf',sha256:'a'.repeat(64)},interior:{url:'https://example.invalid/interior.pdf',sha256:'b'.repeat(64)}}};
test('Lulu timeout enters reconciliation state; no blind resubmission',async()=>{const db=database();let calls=0;const service=createService({MODE:'sandbox',ADMIN_TOKEN:admin,DB:db,STRIPE_KEY:'sk_test_fixture'},{submit:async()=>{calls++;throw new Error('timeout');},getJob:async id=>({id,external_id:orderId,status:{name:'CREATED'}})},{items:[approvedFixture]});const orderId=crypto.randomUUID();const data={...body(),items:[approvedFixture],total:100,currency:'EUR',simulation:false};await db.prepare('INSERT INTO orders (id,token,created,updated,status,data) VALUES (?,?,?,?,?,?)').bind(orderId,'token','2026','2026','PAID',JSON.stringify(data)).run();assert.equal((await service.submit(orderId)).status,'SUBMISSION_UNKNOWN');await assert.rejects(()=>service.submit(orderId));assert.equal(calls,1);assert.equal((await service.reconcile(orderId,'123')).status,'PRINT_SUBMITTED');db.close();});
test('print submission rechecks revoked approval, changed hashes and integration fixtures before provider calls',async()=>{
  for(const change of ['revoked','changed','fixture','empty']){
    const db=database();let calls=0;const current=structuredClone(approvedFixture);
    if(change==='revoked')current.approved=false;
    if(change==='changed')current.print_assets.cover.sha256='c'.repeat(64);
    const service=createService({MODE:'sandbox',ADMIN_TOKEN:admin,DB:db,STRIPE_KEY:'sk_test_fixture'},{submit:async()=>{calls++;return {id:123};}},{items:[current]});
    const id=crypto.randomUUID(),data={items:change==='empty'?[]:[approvedFixture],currency:'EUR',integration_fixture:change==='fixture'};
    await db.prepare('INSERT INTO orders (id,token,created,updated,status,data) VALUES (?,?,?,?,?,?)').bind(id,crypto.randomUUID(),'2026','2026','PAID',JSON.stringify(data)).run();
    await assert.rejects(()=>service.submit(id));assert.equal(calls,0);assert.equal((await service.get(id)).status,'PAID');db.close();
  }
});
test('signed webhook route persists payment and drafts once and rejects unsigned and live events',async()=>{
  const db=database(),secret='fixture-webhook-signing-secret',id=crypto.randomUUID();
  const service=createService({MODE:'sandbox',ADMIN_TOKEN:admin,DB:db,STRIPE_WEBHOOK_SECRET:secret,STRIPE_KEY:'sk_test_fixture'},{});
  const data={email:'reader@example.invalid',address:{country_code:'DE'},items:[],total:100,currency:'EUR',delivery:0};
  await db.prepare('INSERT INTO orders (id,token,created,updated,status,data,session_id) VALUES (?,?,?,?,?,?,?)').bind(id,crypto.randomUUID(),'2026','2026','PAYMENT_PENDING',JSON.stringify(data),'cs_test_fixture').run();
  const payload={id:'evt_fixture',livemode:false,type:'checkout.session.completed',data:{object:{id:'cs_test_fixture',client_reference_id:id,amount_total:100,currency:'eur',livemode:false,payment_status:'paid',payment_intent:'pi_fixture'}}};
  const send=async(value,signed=true)=>{const raw=JSON.stringify(value),t=Math.floor(Date.now()/1000),sig=createHmac('sha256',secret).update(`${t}.${raw}`).digest('hex');return service.route(new Request('http://127.0.0.1:8093/api/webhooks/stripe',{method:'POST',headers:signed?{'Stripe-Signature':`t=${t},v1=${sig}`}:{},body:raw}));};
  assert.equal((await send(payload,false)).status,503);assert.equal((await send({...payload,livemode:true})).status,409);
  assert.equal((await send(payload)).status,200);assert.equal((await service.get(id)).status,'PAID');assert.equal((await (await send(payload)).json()).duplicate,true);
  assert.equal((await db.prepare('SELECT * FROM documents').all()).results.length,1);assert.equal((await db.prepare('SELECT * FROM outbox').all()).results.length,1);db.close();
});
test('out of order provider status cannot regress shipping',async()=>{const {service,db}=fixture();const q=await prepared(service);await service.submit(q.id);await service.poll(q.id,'SHIPPED');await service.poll(q.id,'IN_PRODUCTION');assert.equal((await service.get(q.id)).status,'SHIPPED');db.close();});
test('unknown and rejected Lulu statuses require operator review',async()=>{const {service,db}=fixture();const q=await prepared(service);await service.submit(q.id);await service.poll(q.id,'REJECTED');assert.equal((await service.get(q.id)).status,'PRINT_SUBMITTED');assert.equal((await db.prepare("SELECT * FROM events WHERE kind='PROVIDER_FAILURE_REVIEW'").all()).results.length,1);db.close();});
test('sandbox fails closed without approved products; live mode and live Stripe key prohibited',async()=>{const db=database();assert.throws(()=>createService({MODE:'production',ADMIN_TOKEN:admin,DB:db}));assert.throws(()=>providers({MODE:'sandbox',STRIPE_KEY:'sk_live_fixture'}));const service=createService({MODE:'sandbox',ADMIN_TOKEN:admin,DB:db,STRIPE_KEY:'sk_test_fixture'},{});await assert.rejects(()=>service.quote(body()));db.close();});
test('Stripe HMAC accepts valid signature and rejects replay, forged and stale payload',async()=>{const raw='{"test":true}';const secret='test-webhook-secret';const t=Math.floor(Date.now()/1000);const signature=createHmac('sha256',secret).update(`${t}.${raw}`).digest('hex');await stripeSignature(raw,`t=${t},v1=${signature}`,secret);await assert.rejects(()=>stripeSignature(raw+' ',`t=${t},v1=${signature}`,secret));await assert.rejects(()=>stripeSignature(raw,`t=${t-301},v1=${signature}`,secret));await assert.rejects(()=>stripeSignature(raw,`t=${t},v1=bad`,secret));});
test('currency parsing uses exact cents and refuses unsupported precision',()=>{assert.equal(cents('12.34'),1234);assert.equal(cents('0.75'),75);assert.equal(cents('12'),1200);for(const v of ['1.001','NaN','-1','1e4'])assert.throws(()=>cents(v));});
test('queue processes confirmed orders and excludes uncertain submissions',async()=>{const {service,db}=fixture();const q=await prepared(service);await service.processQueue();assert.equal((await service.get(q.id)).status,'PRINT_SUBMITTED');await service.processQueue();assert.equal((await service.get(q.id)).status,'SHIPPED');db.close();});
test('completed orders do not occupy the ten fulfillment queue slots',async()=>{
  const {service,db}=fixture();
  for(let i=0;i<11;i++)await db.prepare('INSERT INTO orders (id,token,created,updated,status,data) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),crypto.randomUUID(),'2020','2020','SHIPPED','{}').run();
  const q=await prepared(service);
  const processed=await service.processQueue();
  assert.equal(processed.length,1);
  assert.equal((await service.get(q.id)).status,'PRINT_SUBMITTED');
  db.close();
});
test('pending and timed out refunds remain reserved and cannot be duplicated',async()=>{
  for(const timeout of [false,true]) {
    const db=database();let calls=0;const service=createService({MODE:'sandbox',ADMIN_TOKEN:admin,DB:db,STRIPE_KEY:'sk_test_fixture'},{refund:async()=>{calls++;if(timeout)throw new Error('timeout');return {id:'re_test_fixture',status:'pending'};}});
    const id=crypto.randomUUID();await db.prepare('INSERT INTO orders (id,token,created,updated,status,data) VALUES (?,?,?,?,?,?)').bind(id,'token','2026','2026','PAID',JSON.stringify({email:'reader@example.invalid',items:[],total:100,currency:'EUR',payment_intent:'pi_test_fixture'})).run();
    const input={amount:100,request_id:'refund-stable-id'};await service.refund(await service.get(id),input);assert.equal((await service.get(id)).refunded,100);assert.notEqual((await service.get(id)).status,'REFUNDED');await assert.rejects(async()=>service.refund(await service.get(id),input));assert.equal(calls,1);db.close();
  }
});
test('website preview wiring never creates a live link',async()=>{
  const {default:module}=await import('../website.cjs');assert.equal(module.previewUrl('en',null,{}),null);assert.equal(module.previewUrl('en',null,{AETERNUS_SHOP_PREVIEW:'1',AETERNUS_SITE_MODE:'production'}),null);assert.equal(module.previewUrl('en',null,{AETERNUS_SHOP_PREVIEW:'1'}),'http://127.0.0.1:8093/shop/?lang=en');
});
test('private cloud worker stays inaccessible until fully configured',async()=>{
  const {default:worker}=await import('../worker.mjs');assert.equal((await worker.fetch(new Request('https://shop.example.com/'),{})).status,503);
  assert.equal((await worker.fetch(new Request('https://shop.example.com/'),{MODE:'sandbox',ACCESS_AUDIENCE:'test',ADMIN_TOKEN:admin,PRIVATE_DEPLOYMENT_VERIFIED:'true',ACCESS_ISSUER:'https://test.cloudflareaccess.com'})).status,401);
});
